name: nemrod
favicon: null
layout_spectrum: 0.11203
typography_spectrum: 0.31071
title: nemrod
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1eada'
    - '#454440'
    - '#64635f'
    - '#7f7c77'
    - '#cac6ba'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0.08552305749617517
purpose: []
