name: nemrod
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31071
title: nemrod
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00071a'
    - '#9bdb7a'
    - '#01400d'
    - '#408c3c'
    - '#20ba77'
  brandStrength: 0.6439212099649012
  lightness: 0.9481350337155163
  saturation: 0.7828640947118402
  rhythmicContrast: 0.08552305749617517
purpose: []
